name: Domain Guard Example and Test Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  domain_guard:
    runs-on: ubuntu-latest

    steps:
      - name: Run Domain Guards Action
        uses: dtschiffman/domain_guards@dschiffman-tests-the-workflow
        with:
          github_token: ${{ github.token }}
          pr_number: ${{ github.event.pull_request.number }}
