name: PR Diff Tasks Example and Test Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  actions: read
  pull-requests: write

jobs:
  pr_diff_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Diff Tasks Action
        uses: NiftySchiftyTools/pr_diff_tasks@main
        with:
          github_token: ${{ github.token }}
          pr_number: ${{ github.event.pull_request.number }}
